### ISSUE TITLE
Toggle on Linux doesn't work properly

### ISSUE THREAD

**Issue by jcrben** [soutar/hyperterm-summon#56]
- [x] I am on the [latest](https://github.com/soutar/hyperterm-summon/releases/latest) hyperterm-summon version
- [x] I have searched the [issues](https://github.com/soutar/hyperterm-summon/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Manjaro Linux using KDE
- **Hyper.app version**: 3.0.2
- **hyperterm-summon version**: 2.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/jcrben/3ee156917cc4d5ea4e25d66e1d74e6b7
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 

---

## Issue

When Hyper is visible in the taskbar, it doesn't toggle. This means that for the toggling to work, I have to make sure to toggle it so that it is hidden before switching to another window.

### Steps to Reproduce

Toggle Hyper to show it. Then click on an app in the taskbar. Then try to toggle Hyper to make it pop up and notice that it doesn't work.

![image](https://user-images.githubusercontent.com/5614134/75119712-4392af80-563a-11ea-9ed1-3304843a9131.png)

Note that I loaded this up in dev and it worked properly from development, but I ran into another issue w/ one of my keyboard shortcuts breaking https://spectrum.chat/zeit/hyper/debugging-advice-keymap-not-firing-in-dev~c9595898-a74a-4b65-a10f-a26eaf2f8a37.

**Comment by dcalhoun** [comment]
Thanks for the report!

>When Hyper is visible in the taskbar, it doesn't toggle. This means that for the toggling to work, I have to make sure to toggle it so that it is hidden before switching to another window.

Just to be clear, are you stating that "summoning" the window only works if you hide it prior to switching to another application? If not, please help me understand what I am missing.

**Comment by jcrben** [comment]
Yes. It also works if it's visible in the taskbar and focused. And when I'm running this in dev (`yarn run dev` and `yarn run app` of the Hyper repo), it toggles properly.

**Comment by dac09** [comment]
Any ideas on how to fix this? Happy to help if I can

**Comment by dcalhoun** [comment]
@dac09 my only thought is that maybe Hyper, while running on Linux, reports focused windows differently, which could lead to a different outcome when [determining if Hyper's windows should be shown or hidden](https://github.com/soutar/hyperterm-summon/blob/2f27204103f4ab6b0c7fcc61bd0cfc3c29ab82f7/modules/toggle.js#L4-L6). My recommendation would be to place a few logs into this package's source and see which methods are being called when this issue occurs. Hyper is an Electron app, so you can open the dev tools like you would in a Chrome browser (e.g. <kbd>CMD</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> on macOS).

I do not have a Linux machine, so I have not been able to replicate or debug this issue myself. If you'd like to investigate and/or propose a fix, I'd welcome it. You can clone this repository and [load it locally](https://hyper.is/#extensions-module-loading) so that your changes show up in your Hyper app. You can also [run Hyper itself in development mode](https://github.com/vercel/hyper#contribute), if you find it helpful for debugging, though may not be necessary.

**Comment by dac09** [comment]
Hey @dcalhoun, thanks for the tips. I'm loading summon locally now (verified by changing package.json version). But I don't see console logs in the hyper developer tools. Any suggestions here? Sorry if its a silly question!

However, I seem to have a better reproduction this time:
- if I click outside of hyper, next time i run the shortcut it does **not** work
- if I blur hyper using the shortcut first, it works

which leads me the believe the problem maybe triggered by whatever function is handling the system onBlur

**Comment by dcalhoun** [comment]
@dac09

> But I don't see console logs in the hyper developer tools - I've pepperred the summon code with console logs everywhere!

I likely just misremembered where/how logs show up. It has been awhile since I worked on a Hyper plugin. It would appear that running Hyper itself in development mode is required to see logs to the console. After I cloned and built the Hyper repository, they show up in the server from running the `yarn run app` command. They did not show up in the Electron devtools.

<img width="540" alt="Screen Shot 2020-07-25 at 13 06 26" src="https://user-images.githubusercontent.com/438664/88463360-d0ef5f80-ce77-11ea-8811-819614b0c03e.png">

> However, I seem to have a better reproduction this time:
> 
> * if I click outside of hyper, next time i run the shortcut it does **not** work
> * if I blur hyper using the shortcut first, it works
> 
> which leads me the believe the problem maybe triggered by whatever function is handling the system onBlur

Thanks for the additional research. This is helpful information. You may be correct that the issue is related to how the `onBlur` handler executes on Linux.

My recommendation would be to clone Hyper's repository and get it running with `hyperterm-summon` set up as a "local plugin."

1. Clone Hyper and set it up for [local development](https://github.com/vercel/hyper#contribute).
1. Follow its [plugins guide](https://github.com/vercel/hyper/blob/canary/PLUGINS.md) to set up `hypterterm-summon` as a local plugin.
1. Place a few more console logs into `hyperterm-summon` and observe if/how they show up in the `yarn run app` server log.

Let me know if you discover anything of note. A few questions I might as are...

What happens if you click outside of Hyper and then run the short multiple times? Does it ever work? Is it attempting to hide or show the windows or merely not firing a callback at all (add logs to find out)?
