### ISSUE TITLE
Plugin fails to load on Apple ARM M1 chip computers

### ISSUE THREAD

**Issue by beamercola** [soutar/hyperterm-summon#61]
Maybe it's a me-problem, but right now my key command doesn't seem to do anything.

I just set it up on an intel mac last week with no issues

**Comment by dcalhoun** [comment]
@beamercola sorry to hear of the troubles. It is helpful to have all of the details requested within [the Issue template included in this project](https://raw.githubusercontent.com/soutar/hyperterm-summon/master/.github/issue_template.md). It would appear you removed all of those prompts from this issue you created. Not having that information makes it difficult to debug the issue you are experiencing.

That said, if the problem is truly related to Apple's new M1 Macs, I will likely be unable to help. I do not have access M1 Mac. Hopefully someone from the community can contribute and help find a solution.

**Comment by beamercola** [comment]
My bad

- [x] I am on the [latest](https://github.com/soutar/hyperterm-summon/releases/latest) hyperterm-summon version
- [x] I have searched the [issues](https://github.com/soutar/hyperterm-summon/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 11.0.1
- **Hyper.app version**: 3.0.2
- **hyperterm-summon version**: 2.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/beamercola/6f30b93708c9ab89914750f2301feff2
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A

---

## Issue

### Steps to Reproduce

1. Press Ctrl+` if either hyper is focused or not

### Expected Result

The window to hide/show 

### Actual Result

Nothing.  Not sure if there’s somewhere where I can see a log or help debug

**Comment by dcalhoun** [comment]
@beamercola you may have to disable `hideOnBlur` to accomplish this, but are there any errors within the console for Hyper? You should be able access the console in the same manner you would within Chrome (<kbd>CMD</kbd>+<kbd>Option</kbd>+<kbd>I</kbd>).

**Comment by beamercola** [comment]
I changed my config to this, and watched the logs - no console messages
```
  summon: {
    // hideDock: true,
    // hideOnBlur: false,
    hotkey: "Ctrl+`",
  }
```

The odd thing I noticed too is it's still present in the Dock.  I wonder if the plugin isn't being loaded...

Thanks for the help!

**Comment by dcalhoun** [comment]
> The odd thing I noticed too is it's still present in the Dock.  I wonder if the plugin isn't being loaded...

@beamercola by this you mean that no matter whether `hideDock` is set to true or false the icon remains visible in the dock? If so, then yes, it sounds like the plug-in isn't successfully loaded at all. I'd interpret that mean that something low level is causing the plug-in to fail initializing. It's not just the shortcut keybinding that is broken.

I believe the only way to debug what is broken would be to load `hyperterm-summon` as a `localPlugin`. You would need to clone [the Hyper repo](https://github.com/vercel/hyper) and set it up to run in development mode so that you could better debug what is occurring. Unfortunately, I won't be able to do this myself with an M1 Mac.

**Comment by beamercola** [comment]
Thanks for all your help

Great idea running as `localPlugin` - I'll try to mess around with this today and report back asap

**Comment by beamercola** [comment]
Ok I got it running, but not sure if it's any help:

```
➜  hyper git:(canary) yarn run app
yarn run v1.22.10
$ electron target
using config file: /Users/beamer/GitHub/hyper/.hyper.js
Plugin hyperterm-summon (2.0.9) loaded.
Disabling Chromium GPU blacklist
running in dev mode
electron will open file:///Users/beamer/GitHub/hyper/target/index.html
(node:10738) ExtensionLoadWarning: Warnings loading extension at /Users/beamer/Library/Application Support/Hyper/extensions/fmkadmapgofadopljbjfkapdkoienihi: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'minimum_chrome_version'. Unrecognized manifest key 'update_url'. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system. 
(node:10738) ExtensionLoadWarning: Warnings loading extension at /Users/beamer/Library/Application Support/Hyper/extensions/lmhkpmbekcpmknklioeibfkpmmfibljd: Unrecognized manifest key 'commands'. Unrecognized manifest key 'homepage_url'. Unrecognized manifest key 'page_action'. Unrecognized manifest key 'short_name'. Unrecognized manifest key 'update_url'. Permission 'notifications' is unknown or URL pattern is malformed. Permission 'contextMenus' is unknown or URL pattern is malformed. Permission 'tabs' is unknown or URL pattern is malformed. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system. 
Checking for notification messages
ignoring auto updates during dev
Notification messages fetch error SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/beamer/GitHub/hyper/target/node_modules/electron-fetch/lib/index.js:301:55
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[10740:1125/152815.131152:ERROR:gles2_cmd_decoder.cc(4968)] [.RendererMainThread-0x7f85eb822e00]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
[10740:1125/152815.413166:ERROR:gles2_cmd_decoder.cc(4968)] [.RendererMainThread-0x7f85eb822e00]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
```

**Comment by dcalhoun** [comment]
@beamercola unfortunately, no. I do not see anything specific that relates to `hyperterm-summon`. It's likely best to insert debuggers into the source and see if you can identify any specific issues.

Do other plugins load for you successfully?

**Comment by beamercola** [comment]
@dcalhoun I just installed Hyperpower to test with and it seems it's not loading.  Seems like this is a bigger issue with Hyper - thanks for the help - i'll post something over there!
